Blogg-project/blog/urls.py
from django.urls import path
from blog import views
from .views import PostListview,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView,UserPostListView
app_name='blog'


urlpatterns = [
    path('', PostListview.as_view(), name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-detail'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('post/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('user/<str:username>/',UserPostListView.as_view(),name='user-posts'),
    path('likes/',views.like_post,name='like_post'),
]

Blogg-project/blogproj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from users import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('reg/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blogg-project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount,HitCountMixin
# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=100)
    content=models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User,related_name='likes',blank=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


    def total_likes(self):
        return self.likes.count()


    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})




class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.TextField(max_length=200)
    timestamp=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))


# class TrackedPosts(models.Model):
#     post = models.ForeignKey(Post,on_delete=models.CASCADE)
#     ip = models.CharField(max_length=16) #only accounting for ipv4
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#
# class Blog(models.Model):
#     #fields you need
#     blog_views=models.IntegerField(default=0)

Blogg-project/blog/forms.py
from django import forms

from .models import Comment
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content',]

Blogg-project/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,render_to_response
from django.urls import reverse
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Post,Comment
from .forms import CommentForm
from django.views.generic import ListView,DetailView,FormView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.utils import timezone

def home(request):
    context={
        'posts':Post.objects.all()
    }
    return render(request,'blog/home.html',context)

def about(request):
    return render(request,'blog/about.html',{'title': 'About'})


class PostListview(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 2

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    is_liked = False
    form_class = CommentForm
    count_hit=True

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post = context['post']
        post.views = post.views + 1
        if post.likes.filter(id=self.request.user.id).exists():
            context['is_liked'] = True
            context['total_likes'] = post.total_likes()
            context['comment'] = Comment.objects.all()
            context['form']=CommentForm
            context['forms']=True
            context.update({'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:3],})
        return context

    def comment_valid(request, form):
        if request.method != 'POST':
            # No comment submitted
            form = CommentForm()
        else:
            # Comment posted
            form = CommentForm(data=request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.user = request.user
                form.save()
                return HttpResponseRedirect(reverse('blog:blog-home'))


def like_post(request):
    post = get_object_or_404(Post,pk=request.POST.get('post_id'))
    is_liked=False
    if post.likes.filter(pk=request.user.pk).exists():
        post.likes.remove(request.user)
        is_liked=False
    else:
        post.likes.add(request.user)
        is_liked=True
    return HttpResponseRedirect(post.get_absolute_url())

def comment_post(request):
    post = get_object_or_404(Post,pk=request.POST.get('post_id'))
    forms=False
    if post.likes.filter(pk=request.user.pk).exists():
        post.likes.remove(request.user)
        forms=False
    else:
        post.likes.add(request.user)
        forms=True
    return HttpResponseRedirect(post.get_absolute_url())

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post=self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post=self.get_object()
        if self.request.user == post.author:
            return True
        return False

Blogg-project/blog/templates/blog/about.html
{%extends 'blog/base.html'%}
{%block content%}
  <h1>About page</h1>
{%endblock%}

Blogg-project/blog/templates/blog/base.html
{%load static%}
<html lang="en">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%static 'blog/main.css'%}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}

    {% block styles %}

  <style>
      body {

        background: url('{% static "img/1.jpg" %}') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;

      }


  </style>

{% endblock %}


</head>
<body>
    <header class="site-header">
       <nav class="navbar navbar-expand-md navbar-red bg-steel fixed-top" >
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Ravi Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>
<!--              <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>-->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {%if user.is_authenticated%}
                   <a class="nav-item nav-link" href="{%url 'blog:post-create'%}">New post</a>
                   <a class="nav-item nav-link" href="{%url 'logout'%}">Logout</a>
                   <a class="nav-item nav-link" href="{%url 'profile'%}">Profile</a>

                {%else%}
                  <a class="nav-item nav-link" href="{%url 'login'%}">Login</a>
                  <a class="nav-item nav-link" href="{%url 'register'%}">Register</a>
                {%endif%}
            </div>
          </div>
        </div>
      </nav>
    </header>
 <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {%if messages%}
              {%for message in messages %}
                 <div class="alert alert-{{message.tags}}">
                   {{message}}
                 </div>
              {%endfor%}
            {%endif%}
          {% block content %}{% endblock %}
        </div>
<!--        <div class="col-md-4">-->
<!--          <div class="content-section">-->
<!--            <h3>Our Sidebar</h3>-->
<!--            <p class='text-muted'>You can put any information here you'd like.-->
<!--              <ul class="list-group">-->
<!--                <li class="list-group-item list-group-item-light">Latest Posts</li>-->
<!--                <li class="list-group-item list-group-item-light">Announcements</li>-->
<!--                <li class="list-group-item list-group-item-light">Calendars</li>-->
<!--                <li class="list-group-item list-group-item-light">etc</li>-->
<!--              </ul>-->
<!--            </p>-->
<!--          </div>-->
<!--        </div>-->
      </div>
    </main>


 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>

Blogg-project/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{%url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}





{% endblock content %}

Blogg-project/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

Blogg-project/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
        <p class="article-content">{{object.views}}</p>

    </div>
  </article>

   {{total_likes}} Like{{total_likes|pluralize}}

   {%if request.user.is_authenticated%}

   <form action="{%url 'blog:like_post'%}" method="POST">
     {%csrf_token%}
     {%if is_liked%}
       <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-Danger">DisLike</button>
     {%else%}
       <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-primary">Likes</button>
     {%endif%}
   </form>
   {%endif%}


   <br><br>
   <hr>

   <form method="POST" action="">
     {%csrf_token%}
     {{form}}
     <input type="submit" value="Post Comment" class="btn btn-outline-success" >
   </form>

   <div class="main-comment-section">
     {{comment.count}}Comment{{comment|pluralize}}
    {%for comments in comment%}
      <blockquote class="blockquote">
        <p class="mb-0">{{comments.content}}</p>
        <footer class="blockquote-footer">by <cite title="Source Title">{{comments.user|capfirst}}</cite></footer>
      </blockquote>
     {%endfor%}
   </div>
{% endblock %}

Blogg-project/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

Blogg-project/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}